apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

resources:
  - configmap.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: openresty
  app.kubernetes.io/component: ingress
