apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

resources:
  - deployment.yaml

images:
  - name: us-central1-docker.pkg.dev/project-ghost-695752/ghost/ghost-api
    newTag: latest
