apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: dossi
  app.kubernetes.io/component: intelligence-service
