apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: rtt-bridge
  app.kubernetes.io/component: real-time-text
