# Flux GitRepository and Kustomization for syncing
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: project-ghost
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/pyrosec/project-ghost
  ref:
    branch: master
  secretRef:
    name: flux-system
---
# Sync base infrastructure
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ghost-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: project-ghost
  healthChecks:
    - apiVersion: v1
      kind: Namespace
      name: ghost
  timeout: 2m
---
# Sync applications
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ghost-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: ghost-base
  interval: 5m
  path: ./k8s/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: project-ghost
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: redis
      namespace: ghost
    - apiVersion: apps/v1
      kind: StatefulSet
      name: postgres
      namespace: ghost
    - apiVersion: apps/v1
      kind: Deployment
      name: synapse
      namespace: ghost
    - apiVersion: apps/v1
      kind: Deployment
      name: vaultwarden
      namespace: ghost
    - apiVersion: apps/v1
      kind: Deployment
      name: openresty
      namespace: ghost
  timeout: 5m
