apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-config
  namespace: ghost
data:
  PRIMARY_DOMAIN: "pyrosec.is"
  STUN_DOMAIN: "pyrosec.gg"
  STUN_HOST: "pyrosec.gg"
  MATRIX_SERVER_NAME: "pyrosec.is"
  GHOST_NUMBER: "8008888080"
  LOG_LEVEL: "INFO"
  REDIS_URI: "redis://redis:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: asterisk-config
  namespace: ghost
data:
  ASTERISK_UID: "1010"
  ASTERISK_GID: "7087"
  SIP_PORT: "35061"
  RTP_START: "30000"
  RTP_END: "30099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-config
  namespace: ghost
data:
  CERTS_GID: "7077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-config
  namespace: ghost
data:
  SYNAPSE_SERVER_NAME: "pyrosec.is"
  SYNAPSE_REPORT_STATS: "no"
  SYNAPSE_NO_TLS: "1"
  SYNAPSE_ENABLE_REGISTRATION: "yes"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
  namespace: ghost
data:
  MIN_PORT: "49152"
  MAX_PORT: "65535"
  REALM: "pyrosec.gg"
  # DTLS requires fingerprint authentication
  FINGERPRINT: "true"
  LT_CRED_MECH: "true"
  NO_MULTICAST_PEERS: "true"
